package dev.zeroinput.ime.ui

// Generated by tools/prepare-emoji.py from the pinned Unicode 18.0 release.
internal object RgiEmojiVersion {
    const val VERSION = "18.0"
    const val SHA256 = "9b927ee2e07b87fae952b0dbdc61e149ba2e5a2837f330be27d8f686a3208401"
    const val COUNT = 3972
    const val MAX_UTF16_LENGTH = 15
}
